# Setup
title: "Benim Blogum"
baseurl: "/blog"
description: Kendi GitHub Pages blogum
url: "https://afegaming.github.io"
avatar: /profil.png
paginate: 5
permalink: pretty
cover_image: /blog/bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# SEO
twitter:
  username: afegaming
  card: summary
logo: /blog/logo.png
social:
  name: Ahmet Tunahan Demir
  links:
    - https://github.com/afegaming
lang: tr

sass:
  sass_dir: _sass
  style: :compressed

# Options
# google_analytics: UA-000000-0
# disqus: xxxxxx

# Author
author:
  name: Ahmet Tunahan Demir
  url: https://github.com/afegaming/
